version: '3.9'

services:
  mongodb:
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017 #puerto por el que mongo usa
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=2332
    volumes:
      - /mongo_data:/data/db
volumes:
  mongo_data: