version: '3.9'

services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: krowfotografia-mongo
    hostname: host-mongo
    ports:
      - 27017:27017 #puerto por el que mongo usa
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=2332
    volumes:
      - /data:/data/db
      - /data/log:/var/log/mongodb/